// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJZnJyKdGlBbgmpCWVIMvKk0ZXBRaZhkg',
    appId: '1:851276842753:web:276e21388e5c091044fd00',
    messagingSenderId: '851276842753',
    projectId: 'fir-starter-4841a',
    authDomain: 'fir-starter-4841a.firebaseapp.com',
    storageBucket: 'fir-starter-4841a.appspot.com',
    measurementId: 'G-B414SNQNGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNIyRsAuq1Tw2qXCV9ATl-wY0iUR1i5I',
    appId: '1:851276842753:android:90ed66d39c4f6ced44fd00',
    messagingSenderId: '851276842753',
    projectId: 'fir-starter-4841a',
    storageBucket: 'fir-starter-4841a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1i3oas9N8gxbTKkyl140S6ujhy9rzad4',
    appId: '1:851276842753:ios:355aaf30550a5f5844fd00',
    messagingSenderId: '851276842753',
    projectId: 'fir-starter-4841a',
    storageBucket: 'fir-starter-4841a.appspot.com',
    iosBundleId: 'com.example.socialMideaFlutter',
  );
}
